# Numpy Array

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
#تعداد ۵ عدد از ۱ تا ۲ با فاصله های مساوی
np.linspace(1,2,5)
#در این تابع اعداد تولید شده شامل عدد نهایی هم می شود

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
#np.random.-func-
np.random.rand(5)
#توزیع یکنواخت گسسته

array([0.57455976, 0.47655373, 0.82108061, 0.0447401 , 0.19214079])

In [18]:
np.random.rand(3,5)
#توزیع یکنواخت گسسته

array([[0.58601464, 0.86810166, 0.32425701, 0.03801662, 0.70724999],
       [0.96500528, 0.26285114, 0.60724723, 0.69740251, 0.47973261],
       [0.04475783, 0.72124484, 0.71050294, 0.92476321, 0.72233442]])

In [19]:
np.random.randn(5)
#توزیع نرمال استاندارد

array([-0.42644894,  0.25104967, -0.58995312, -0.17591622,  0.76960382])

In [20]:
np.random.randn(3,5)
#توزیع نرمال استاندارد

array([[-2.11689257, -0.00724744,  0.99201183, -1.21233034,  0.9337687 ],
       [ 0.60093465, -1.06147297, -0.79010007, -0.0696095 , -1.54614436],
       [-1.12139951, -0.27785416, -0.59700368, -0.24065664, -3.23120085]])

In [22]:
np.random.randint(1,30)

28

In [23]:
np.random.randint(1,30,5)

array([ 4, 26,  3, 15,  9])

In [24]:
#np.random.normal(avg,varianse,number)
np.random.normal(5,2,8)

array([7.27165235, 5.98669481, 3.67409908, 5.62460925, 7.085797  ,
       5.46070669, 4.33184809, 6.25326398])

In [27]:
A=np.random.normal(5,2,15)

In [28]:
A.reshape(3,5)

array([[1.17406651, 2.06598345, 5.31717901, 5.00641122, 4.95751927],
       [7.79712238, 9.80519521, 3.23320977, 2.60858546, 5.48144005],
       [3.24684665, 4.97690341, 4.13702164, 6.25001386, 4.64278613]])

In [39]:
np.random.normal(5,2,15).reshape(3,5)  
#3 and 5 in reshape must be relevant to 15 in normal function

array([[6.17134038, 7.79301805, 5.41365754, 4.11237831, 3.12395895],
       [3.56172622, 5.01600301, 3.79910541, 6.48368745, 4.44421208],
       [2.14779062, 0.05647258, 6.00667582, 2.16315168, 5.53348937]])

In [30]:
A.max()

9.805195207696734

In [32]:
A.min()

1.1740665091472846

In [33]:
#max index
A.argmax()

6

In [34]:
#min index
A.argmin()

0

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [44]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [45]:
the_list=[[0,1,2],[3,4,5],[6,7,8]]
np.array(the_list)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.random.randn(25)

array([ 0.40850445, -0.01672095, -1.91928795,  0.7213306 ,  0.40812015,
        0.83773234, -0.51971391, -1.43732595, -0.64082059,  0.13863722,
        1.0420784 , -1.29108232, -1.49921417,  0.81081424,  1.28698498,
       -0.9181564 ,  2.19226641, -1.13279772,  1.04894065, -0.98645518,
        0.12187622,  0.38008329,  1.2474822 ,  0.34265362,  0.0950456 ])

In [47]:
np.random.randn(5,5)

array([[ 0.60151527, -0.32080467, -1.44797316,  0.07632975,  0.15086392],
       [ 0.23519216, -0.69100412, -0.91188713,  0.51657453,  1.13823844],
       [ 1.04684812,  0.32216748, -0.92226119,  0.61064465,  0.17808271],
       [-0.15058619,  1.05990327, -0.15018597,  0.68055432, -1.91941614],
       [ 1.1418906 , -0.40064299,  1.5921467 , -0.34979739, -0.53307376]])

In [48]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [49]:
np.random.normal(10,3,20).reshape(4,5)

array([[11.57828415,  9.56409592,  7.07207605, 10.84769532, 14.62552722],
       [11.91915988,  8.62621153, 12.62309731, 11.47800107, 13.38368874],
       [13.29293908, 13.45817876, 10.87977518, 14.55176382, 10.19890888],
       [ 7.90300556,  6.84633466,  7.0882933 ,  8.32314166, 14.03276561]])

# 2-indexing and selection

In [52]:
A=np.random.randint(1,10,10)
A

array([4, 8, 9, 2, 6, 1, 5, 2, 4, 7])

In [53]:
A[3]

2

In [54]:
A[2:5]

array([9, 2, 6])

In [55]:
AA=np.array([[5,10,15],[20,25,30],[35,40,45]])
AA

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
AA[1][2]

30

In [57]:
AA[1,2]

30

In [60]:
AA[1:3,0:2]

array([[20, 25],
       [35, 40]])

In [59]:
AA[1:3,1:3]

array([[25, 30],
       [40, 45]])

# 3-conditional selection

In [61]:
A

array([4, 8, 9, 2, 6, 1, 5, 2, 4, 7])

In [62]:
A>5

array([False,  True,  True, False,  True, False, False, False, False,
        True])

In [63]:
A[A>5]

array([8, 9, 6, 7])

In [64]:
A[A<4]

array([2, 1, 2])

# 4-mathematical operations

In [66]:
B=np.arange(11)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
B+B

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [68]:
B-B

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
B*B

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [70]:
B/B

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
B+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
B*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [73]:
B**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [74]:
1/B

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])